# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160311_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricesinevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Events')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Wares')),
            ],
        ),
    ]
