# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_wares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=200)),
                ('eventinfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Waregroups',
            fields=[
                ('wgid', models.AutoField(primary_key=True, serialize=False)),
                ('wgname', models.CharField(max_length=200)),
                ('wginfo', models.CharField(max_length=200)),
            ],
        ),
    ]
