# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wares',
            fields=[
                ('wareid', models.AutoField(primary_key=True, serialize=False)),
                ('warename', models.CharField(max_length=200)),
                ('inbar', models.IntegerField(default=0)),
                ('instockroom', models.IntegerField(default=0)),
            ],
        ),
    ]
